### ISSUE TITLE
Gradle dependencies

### ISSUE THREAD

**Issue by nicolasfara** [QuietOne/MonkeyBrains#3]
Hi,
Could you please create a gradle dependency for this framework in order to import it in jMonkeyEngine projects?

Thanks! :)

**Comment by Pesegato** [comment]
Nicolas, 'scoltame qua: lassa stare 'sta libreria che te perdi solo che tempo... a parte gli scherzi: se vuoi imparare scaricati i sorgenti, compilali e studiali. Ma ti avviso che se vuoi farci qualcosa di produttivo la dovrai in buona parte riscrivere. In ogni caso io non ci farò il gradle
